CREATE TABLE `LOG` (
  `ID` char(36) NOT NULL COMMENT '主键ID',
  `APP_NAME` char(36) NOT NULL COMMENT '所属应用',
  `LOG_TYPE` int(11) DEFAULT NULL COMMENT '日志类型，0为操作日志，1为异常日志',
  `USER` varchar(100) DEFAULT NULL COMMENT '访问者/请求者',
  `METHOD_NAME` varchar(100) DEFAULT NULL COMMENT '方法名',
  `REQUEST_PARAMS` varchar(500) DEFAULT NULL COMMENT '请求参数',
  `METHOD_DESCRIPTION` varchar(100) DEFAULT NULL COMMENT '方法描述',
  `REQUEST_IP` varchar(50) DEFAULT NULL COMMENT '访问者IP',
  `REQUEST_URI` varchar(200) DEFAULT NULL COMMENT '请求URI',
  `REQUEST_PATH` varchar(200) DEFAULT NULL COMMENT '请求PATH',
  `EXCEPTION_CODE` varchar(100) DEFAULT NULL COMMENT '异常码',
  `EXCEPTION_DETAIL` varchar(100) DEFAULT NULL COMMENT '异常描述',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `STATUS` varchar(200) DEFAULT NULL COMMENT '请求返回状态',
  `CONTENT` longtext COMMENT '请求返回内容',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8